---
# vars file for passwd_history
var_sudo_umask: !!str 0077
var_authselect_profile: !!str minimal
var_password_pam_unix_remember: !!str 2
var_accounts_passwords_pam_faillock_deny: !!str 3
var_accounts_passwords_pam_faillock_fail_interval: !!str 900
var_accounts_passwords_pam_faillock_unlock_time: !!str 900
var_password_pam_dcredit: !!str -1
var_password_pam_lcredit: !!str -1
var_password_pam_minclass: !!str 4
var_password_pam_minlen: !!str 15
var_password_pam_ocredit: !!str -1
var_password_pam_retry: !!str 3
var_password_pam_ucredit: !!str -1
var_password_hashing_algorithm_pam: !!str sha512
var_logind_session_timeout: !!str 600
var_accounts_password_minlen_login_defs: !!str 15
var_accounts_maximum_age_root: !!str 365
var_password_pam_unix_rounds: !!str 65536
var_accounts_tmout: !!str 600
var_user_initialization_files_regex: !!str ^(\.bashrc|\.zshrc|\.cshrc|\.profile|\.bash_login|\.bash_profile)$
var_l1tf_options: !!str full,force
var_rng_core_default_quality: !!str 500
var_spec_store_bypass_disable_options: !!str seccomp
sysctl_net_ipv6_conf_all_accept_ra_defrtr_value: !!str 0
sysctl_net_ipv6_conf_all_accept_ra_pinfo_value: !!str 0
sysctl_net_ipv6_conf_all_accept_ra_rtr_pref_value: !!str 0
sysctl_net_ipv6_conf_all_accept_redirects_value: !!str 0
sysctl_net_ipv6_conf_all_accept_source_route_value: !!str 0
sysctl_net_ipv6_conf_all_autoconf_value: !!str 0
sysctl_net_ipv6_conf_all_max_addresses_value: !!str 1
sysctl_net_ipv6_conf_all_router_solicitations_value: !!str 0
sysctl_net_ipv6_conf_default_accept_ra_defrtr_value: !!str 0
sysctl_net_ipv6_conf_default_accept_ra_pinfo_value: !!str 0
sysctl_net_ipv6_conf_default_accept_ra_rtr_pref_value: !!str 0
sysctl_net_ipv6_conf_default_accept_redirects_value: !!str 0
sysctl_net_ipv6_conf_default_accept_source_route_value: !!str 0
sysctl_net_ipv6_conf_default_autoconf_value: !!str 0
sysctl_net_ipv6_conf_default_max_addresses_value: !!str 1
sysctl_net_ipv6_conf_default_router_solicitations_value: !!str 0
sysctl_net_ipv4_conf_all_accept_redirects_value: !!str 0
sysctl_net_ipv4_conf_all_accept_source_route_value: !!str 0
sysctl_net_ipv4_conf_all_arp_filter_value: !!str 0
sysctl_net_ipv4_conf_all_arp_ignore_value: !!str 2
sysctl_net_ipv4_conf_all_rp_filter_value: !!str 1
sysctl_net_ipv4_conf_all_secure_redirects_value: !!str 0
sysctl_net_ipv4_conf_all_shared_media_value: !!str 0
sysctl_net_ipv4_conf_default_accept_redirects_value: !!str 0
sysctl_net_ipv4_conf_default_accept_source_route_value: !!str 0
sysctl_net_ipv4_conf_default_rp_filter_value: !!str 1
sysctl_net_ipv4_conf_default_secure_redirects_value: !!str 0
sysctl_net_ipv4_conf_default_shared_media_value: !!str 0
sysctl_net_ipv4_icmp_ignore_bogus_error_responses_value: !!str 1
sysctl_net_ipv4_tcp_rfc1337_value: !!str 1
sysctl_net_ipv4_tcp_syncookies_value: !!str 1
sysctl_kernel_kptr_restrict_value: !!str 2
var_slub_debug_options: !!str FZP
var_selinux_state: !!str enforcing
var_polyinstantiation_enabled: !!str true
var_postfix_root_mail_alias: !!str change_me@localhost
var_postfix_inet_interfaces: !!str loopback-only