---
# vars file for passwd_enforce
var_password_pam_dcredit: !!str -1
var_password_pam_lcredit: !!str -1
var_password_pam_minclass: !!str 4
var_password_pam_minlen: !!str 15
var_password_pam_ocredit: !!str -1
var_password_pam_retry: !!str 3
var_password_pam_ucredit: !!str -1
