---
# vars file for lock_account
var_sudo_umask: !!str 0077
var_authselect_profile: !!str minimal
var_password_pam_unix_remember: !!str 2
var_accounts_passwords_pam_faillock_deny: !!str 3
var_accounts_passwords_pam_faillock_fail_interval: !!str 900
var_accounts_passwords_pam_faillock_unlock_time: !!str 900
var_password_pam_dcredit: !!str -1
var_password_pam_lcredit: !!str -1
var_password_pam_minclass: !!str 4
var_password_pam_minlen: !!str 15
var_password_pam_ocredit: !!str -1
var_password_pam_retry: !!str 3
var_password_pam_ucredit: !!str -1
var_password_hashing_algorithm_pam: !!str sha512
var_logind_session_timeout: !!str 600
var_accounts_password_minlen_login_defs: !!str 15
var_accounts_maximum_age_root: !!str 365
var_password_pam_unix_rounds: !!str 65536
var_accounts_tmout: !!str 600
var_user_initialization_files_regex: !!str ^(\.bashrc|\.zshrc|\.cshrc|\.profile|\.bash_login|\.bash_profile)$
var_l1tf_options: !!str full,force
var_rng_core_default_quality: !!str 500